# Generated by Django 5.2.8 on 2025-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_route_gallery_route_image_url_alter_route_ai_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyinput',
            name='personal_interest',
            field=models.JSONField(db_column='personal_interests'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dangers',
            field=models.JSONField(blank=True, db_column='dangers_snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='personal_interest',
            field=models.JSONField(db_column='personal_interests'),
        ),
        migrations.AlterModelTable(
            name='historyinput',
            table='history_inputs',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
    ]
