class VietnamData {
  static const List<String> provinces = [
    "Lai Châu",
    "Lào Cai",
    "Sơn La",
    "Yên Bái",
    "Hà Giang",
    "Cao Bằng",
    "Quảng Ninh",
    "Bắc Giang",
    "Hà Nội",
    "Ninh Bình",
    "Quảng Bình",
    "Thanh Hóa",
    "Nghệ An",
    "Thừa Thiên Huế",
    "Kon Tum",
    "Gia Lai",
    "Đắk Lắk",
    "Lâm Đồng",
    "Ninh Thuận",
    "Khánh Hòa",
    "Tây Ninh",
    "Bà Rịa – Vũng Tàu",
  ];
}